# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests on LTS version of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
    paths:
      - 'backend/**'
  pull_request:
    branches: ['main']
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use LTS Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run linter
        working-directory: backend
        run: npm run lint

      - name: Build project
        working-directory: backend
        run: npm run build

      - name: Run tests
        working-directory: backend
        run: npm run test
